verbatim:
  cabal-version: 3.0

license: BSD-3-Clause
license-file: LICENSE
name: "hcat"
version: 0.1
synopsis: "An example command line pager written in Haskell"
homepage: https://effective-haskell.com
author: Rebecca Skinner
maintainer: rebecca@rebeccaskinner.net

default-extensions:
  - DerivingStrategies
  - ImportQualifiedPost

ghc-options:
  - -Wall -Wno-missing-home-modules -Wno-type-defaults

library:
  source-dirs: src
  ghc-options: -O2
  dependencies:
    - base
    - text
    - bytestring
    - process
    - directory
    - time

executable:
  source-dirs: app
  main: Main.hs
  ghc-options: -O2
  dependencies:
    - base
    - hcat

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - hspec
      - hcat
